/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.2/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    alias(libs.plugins.kotlin.jvm)
    application
}

repositories {
    mavenCentral()
    mavenLocal()
    maven("https://repo.styx.moe/releases")
}

dependencies {
    implementation(libs.tomlkt)
    // Check the source for it here or build a local distribution if you don't trust me
    // https://github.com/Vodes/Styx-Common
    implementation(libs.styx.common)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.AppKt"
}